services:

  backend:
    build: .
    ports:
      - 8000:8000
    environment:
      - MONGO_URI=mongodb://db:27017/Social_Media_Api
    env_file:
      - .env

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - Social_Media_Api:/data/db

  maildev:
    image: maildev/maildev:2.0.5
    ports:
      - "1080:80"
      - "1025:25"

volumes:
  Social_Media_Api: